### ISSUE TITLE
us-series with Kodi 14.0

### ISSUE THREAD

**Issue by thinkvolt** [bromix/plugin.video.7tv#11]
"This will only work with Helix (Kodi 14.x) because of an updated version of ffmpeg. I could implement a switch based on the current xbmc/kodi version, so people running helix could watch these shows."

I have Helix (14.0) installed, but the us-series (NCIS, Homeland, ...) don`t work. I tried with Openelec & Raspbmc with a RaspberryPi and with Windows.

**Comment by thinkvolt** [comment]
20:35:27 T:4408  NOTICE: -->Python Interpreter Initialized<--
20:35:27 T:6832  NOTICE: DVDPlayer: Opening: http://ws.vtc.sim-technik.de/video/playlist.m3u8?ClipID=3602884&token=00~36f9c4~36f9c4~54aae77f~15180~0-8552ac0a1a520da98b5afdab7&ts=1420486527
20:35:28 T:6832 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
20:35:28 T:6832  NOTICE: DXVA::CProcessorHD::PreInit - The Direct3d device doesn't support DXVA-HD.
20:35:28 T:6832  NOTICE: CWinRenderer::Preinit - could not init DXVA-HD processor - skipping
20:35:28 T:1500  NOTICE: Thread DVDPlayer start, auto delete: false
20:35:28 T:1500  NOTICE: Creating InputStream
20:35:28 T:6244  NOTICE: Thread FileCache start, auto delete: false
20:35:28 T:1500  NOTICE: Creating Demuxer
20:35:28 T:1500   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_github.com	FALSE	/	TRUE	0	_gh_s	'
20:35:28 T:1500   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_github.com	FALSE	/	TRUE	0	_	'
20:35:28 T:1500   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_github.com	FALSE	/	TRUE	0	_gh_se	'
20:35:28 T:1500   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_github.com	FALSE	/	TRUE	0	_gh_ses	'
20:35:28 T:1500   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_github.com	FALSE	/	TRUE	0	_gh_	'
20:35:28 T:1500   ERROR: CCurlFile::GetCookies - invalid cookie: 'ithub.com	FALSE	/	TRUE	0	_gh_	'
20:35:28 T:1500   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_github.com	FALSE	/	TRUE	0	_g	'
20:35:28 T:1500   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_github.com	FALSE	/	TRUE	0	_gh	'
20:35:28 T:1500   ERROR: CCurlFile::GetCookies - invalid cookie: 'hub.com	FALSE	/	TRUE	0	_	'
20:35:29 T:1500   ERROR: CCurlFile::GetCookies - invalid cookie: 'ALSE	FALSE	/	TRUE	0	_gh	'
20:35:29 T:1500  NOTICE: Opening stream: 0 source: 256
20:35:29 T:1500  NOTICE: Creating video codec with codec id: 28
20:35:29 T:1500  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
20:35:29 T:1500  NOTICE: Creating video thread
20:35:29 T:1500   ERROR: CSelectionStreams::Get - failed to get stream
20:35:29 T:1500 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
20:35:29 T:4172  NOTICE: Thread DVDPlayerVideo start, auto delete: false
20:35:29 T:4172  NOTICE: running thread: video_thread
20:35:29 T:4172  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(640x360)
20:35:29 T:4172  NOTICE: DXVA::CDXVAContext::CreateDecoder - hw may not support multiple decoders, releasing existing ones
20:35:29 T:4172  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(640x360)
20:35:29 T:4172  NOTICE: DXVA::CDXVAContext::CreateDecoder - hw may not support multiple decoders, releasing existing ones
20:35:30 T:4172  NOTICE: DXVA::CDecoder::Close - closing decoder

**Comment by thinkvolt** [comment]
Here: http://pastebin.com/gYy0kg3f

**Comment by thinkvolt** [comment]
Here: http://pastebin.com/gYy0kg3f

 

Gruß

 

Jonas

 

Von: bromix [mailto:notifications@github.com] 
Gesendet: Montag, 5. Januar 2015 21:22
An: bromix/plugin.video.7tv
Cc: thinkvolt
Betreff: Re: [plugin.video.7tv] us-series with Kodi 14.0 (#11)

 

Can ypu please provide a complete log via pastebin.com or similar.

**Comment by bromix** [comment]
Okay...I tried some stuff, but nothing I can do. They adapted :( ASDE Addon also won't work with US-Series. I'm sorry.
