### ISSUE TITLE
Missing Shows

### ISSUE THREAD

**Issue by moneymaker365** [bromix/plugin.video.7tv#12]
I'm missing some shows on ProsiebenMAXX e.g. [Border Patrol][1]. It is up to the App offer?

[1]:http://www.prosiebenmaxx.de/tv/border-patrol-canada/video

**Comment by bromix** [comment]
Yes. If the app doesn't provide it it won't be listed. This has mostly to do with licenses for shows which are different for mobile then for broadcast.
