### ISSUE TITLE
finde 7tv nicht in meiner kodi version

### ISSUE THREAD

**Issue by bananenklops** [bromix/plugin.video.7tv#14]
Hallo, ich habe keine Ahnung ob ich hier richtig bin, aber ich finde nichts im Internet dazu.
Und zwar finde ich das addon 7tv nicht. Ich lese immer nur, dass es in dem offiziellen kodi repo ist, aber das wird bei mir nicht angezeigt, ebensowenig wie myvideo.

**Comment by bromix** [comment]
http://kodi.wiki/view/HOW-TO:Install_add-ons

**Comment by bromix** [comment]
Einmal bitte dem Link oben folgen...dort steht alles wie du Addons installieren kannst.
