### ISSUE TITLE
Langsam

### ISSUE THREAD

**Issue by Crossfire92** [bromix/plugin.video.7tv#17]
Hallo
Auf meinem Raspberry Pi B+ läuft das Add-On extrem langsam. Wenn ich z.B auf die Mediathek von Pro7 navigieren will benötigt es min. 5 Minuten und mehr
Bei jedem klick muss ich 1-3 Minuten warten

Auf dem Raspberry Pi 2 habe ich keine Probleme

Hoffe ihr könnt helfen

**Comment by bromix** [comment]
Please provide a debug log

**Comment by Crossfire92** [comment]
http://pastebin.com/4e0bwCpX

If you need more from the Log file you can ask me. This is the whole part with 7TV in it and a little part before.

Thanks for your help

**Comment by bromix** [comment]
http://kodi.wiki/view/Log_file/Easy
Please follow the guide and enable **Debug Logging** and please provide the complete log. Only a part of it doesn't help.
I can not promise anything by I'm willing to look into the log.
